### ISSUE TITLE
Sugestie

### ISSUE THREAD

**Issue by tomaszdrab** [jakub-galecki/image-processing#1]
Issue na sugestie i pomysły dotyczące kodu

**Comment by tomaszdrab** [comment]
https://github.com/jakub-galecki/image-processing/blob/d377d635cc44b08e1b8241846a735c37f6d86fb6/bmp_img.c#L10
https://github.com/jakub-galecki/image-processing/blob/d377d635cc44b08e1b8241846a735c37f6d86fb6/bmp_img.c#L58
Myślę, że dodanie funkcji o sygnaturach
`BMP *read_bmp(const char* filename);`
`void write_image_by_filename(BMP *bmp_image, const char *filename);`
przyspieszyłoby testowanie.
Funkcje zdają się mieć odwrotne działanie, więc może `image` można zastąpić w nazwie przez `bmp` lub `bmp` przez `image`.

**Comment by jac30b** [comment]
Zmienione
